import json
import os
import requests
import sys

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
GITHUB_REPOSITORY = os.getenv("GITHUB_REPOSITORY")

GIT_INFO = "reports/git_info.json"
VALIDATION = "reports/validation.json"
SUMMARY = "reports/summary.md"

OUTPUT_FILE = "reports/pr.json"


def load_json(file):

    if not os.path.exists(file):
        return {}

    with open(file, encoding="utf-8") as f:
        return json.load(f)


def load_text(file):

    if not os.path.exists(file):
        return ""

    with open(file, encoding="utf-8") as f:
        return f.read()


if not GITHUB_TOKEN:
    print("GITHUB_TOKEN missing")
    sys.exit(1)

if not GITHUB_REPOSITORY:
    print("GITHUB_REPOSITORY missing")
    sys.exit(1)

git = load_json(GIT_INFO)
validation = load_json(VALIDATION)
summary = load_text(SUMMARY)

feature_branch = git.get("feature_branch")

if not feature_branch:

    print("Nothing to create PR for.")
    sys.exit(0)

owner, repo = GITHUB_REPOSITORY.split("/")

title = "AI Terraform Drift Auto Remediation"

body = f"""
# Terraform Drift Auto Remediation

## AI Summary

{summary}

---

## Validation

Terraform Validation : {'✅ Passed' if validation.get('success') else '❌ Failed'}

---

## Generated By

Terraform Drift Detection Agent
"""

url = f"https://api.github.com/repos/{owner}/{repo}/pulls"

headers = {
    "Authorization": f"Bearer {GITHUB_TOKEN}",
    "Accept": "application/vnd.github+json"
}

payload = {
    "title": title,
    "head": feature_branch,
    "base": "main",
    "body": body,
    "maintainer_can_modify": True
}

print("=" * 80)
print("Creating Pull Request")
print("=" * 80)

response = requests.post(
    url,
    headers=headers,
    json=payload
)

if response.status_code not in (200, 201):

    print(response.text)

    sys.exit(1)

pr = response.json()

report = {
    "number": pr["number"],
    "title": pr["title"],
    "url": pr["html_url"],
    "state": pr["state"]
}

os.makedirs("reports", exist_ok=True)

with open(
    OUTPUT_FILE,
    "w",
    encoding="utf-8"
) as f:

    json.dump(report, f, indent=4)

print()
print("Pull Request Created Successfully")
print(pr["html_url"])
